version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=roffidaijoubu@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  microservice-google-tts:
    image: roffidaijoubu/microservice-google-tts:latest
    labels:
      # Main API route
      - "traefik.http.routers.microservice-google-tts.rule=Host(`gtts.oristarium.com`)"
      - "traefik.http.routers.microservice-google-tts.entrypoints=https"
      - "traefik.http.routers.microservice-google-tts.tls.certresolver=myresolver"
      - "traefik.http.routers.microservice-google-tts.middlewares=security-headers,compress"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.microservice-google-tts-http.rule=Host(`gtts.oristarium.com`)"
      - "traefik.http.routers.microservice-google-tts-http.entrypoints=http"
      - "traefik.http.routers.microservice-google-tts-http.middlewares=https-redirect"
      
      # Security headers
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Referrer-Policy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=geolocation=self"
      
      # Compression middleware
      - "traefik.http.middlewares.compress.compress=true"
      
      # HTTPS redirect middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      
      # Service configuration
      - "traefik.http.services.microservice-google-tts.loadbalancer.server.port=3001"
    networks:
      - web
    expose:
      - "3001"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  web:
    external: true 